version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:5000"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.2"
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
